app2/config/routes.rb
App2::Application.routes.draw do
  get "mainpage/index"

  resources :groups
  resources :people
  
  root to: "mainpage#index"

end

app2/app/models/group.rb
class Group < ActiveRecord::Base
	has_many :people, dependent: :destroy
end

app2/app/models/person.rb
class Person < ActiveRecord::Base
	belongs_to :group
	validates_associated :group
	validates :name, uniqueness: { message: "One record only" }
end

app2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app2/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	def new
	end

	def index
		@group = Group.all
	end

	def create
  		@group = Group.new(group_params)
 
  		@group.save
  		redirect_to @group
	end

	def show
		@group = Group.find(params[:id])
	end

	def destroy
		@group = Group.find(params[:id])
  		@group.destroy
 
  		redirect_to groups_path
	end
 
	private
  		def group_params
    		params.require(:group).permit(:groupname)
  		end
end

app2/app/controllers/mainpage_controller.rb
class MainpageController < ApplicationController
  def index
  end
end

app2/app/controllers/people_controller.rb
class PeopleController < ApplicationController
	def  new
		@person = Person.new
	end

	def index
		@person = Person.all
		@group = Group.all
	end

	def create
  		@person = Person.new(person_params)
  		if @person.save
  			redirect_to @person
  		else
  			render 'new'
  		end
	end

	def show
		@person = Person.find(params[:id])
	end

	def destroy
		@person = Person.find(params[:id])
  		@person.destroy
 
  		redirect_to people_path
	end
 
	private
  		def person_params
    		params.require(:person).permit(:name, :address, :telephone, :group_id)
  		end
end

app2/app/helpers/application_helper.rb
module ApplicationHelper
end

app2/app/helpers/groups_helper.rb
module GroupsHelper
end

app2/app/helpers/mainpage_helper.rb
module MainpageHelper
end

app2/app/helpers/people_helper.rb
module PeopleHelper
end

app2/app/views/groups/index.html.erb
<h1>Listing Groups</h1>
 
<table>
  <tr>
    <th>Group ID</th>
    <th>Groupname</th>
  </tr>
 
  <% @group.each do |groups| %>
    <tr>
      <td><center><%= groups.id %></center></td>
      <td><center><%= groups.groupname %></center></td>
       <td><%= link_to 'Show', groups %></td>
      <td><%= link_to 'Destroy', group_path(groups),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
<%= link_to 'Add New Group', new_group_path %>
<br>
<%= link_to 'Home', root_path %>

app2/app/views/groups/new.html.erb
<h1>Create a Group</h1>

<%= form_for :group, url: groups_path do |f| %>
  <p>
    <%= f.label :groupname %><br>
    <%= f.text_field :groupname %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app2/app/views/groups/show.html.erb
<p>
  <strong>Group ID:</strong>
  <%= @group.id %>
</p>

<p>
  <strong>Groupname:</strong>
  <%= @group.groupname %>
</p>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Telephone</th>
  </tr>
 
  <% @group.people.each do |person| %>
    <tr>
      <td><%= person.name %></td>
      <td><%= person.address %></td>
      <td><%= person.telephone %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Back to List', groups_path %>
 

app2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app2/app/views/mainpage/index.html.erb
<h1>New Project</h1>
<p>Show the group and the people associated with it</p>
<%= link_to "Show Group", controller: "groups" %>
<%= link_to "Show People", controller: "people" %>

app2/app/views/people/index.html.erb
<h1>List of People</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Telephone</th>
    <th>Group Name</th>
  </tr>
 
  <% @person.each do |people| %>
    <tr>
      <td><%= people.name %></td>
      <td><%= people.address %></td>
      <td><%= people.telephone %></td>
      <td><%= people.group.groupname %></td>
       <td><%= link_to 'Delete', person_path(people), method: :delete, data: { confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Add New People', new_person_path %>
<%= link_to 'Home', root_path %>

app2/app/views/people/new.html.erb
<h1>Yollo</h1>
<p>Create New Person Here</p>

<%= form_for :person, url: people_path do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited
      this post from being saved:</h2>
      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>
 
  <p>
    <%= f.label :telephone %><br>
    <%= f.text_field :telephone %>
  </p>

  </p>
  <%= f.label :groupname %>
  <%= f.collection_select(:group_id, Group.all, :id, :groupname) %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app2/app/views/people/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @person.address %>
</p>
 
<p>
  <strong>Telephone:</strong>
  <%= @person.telephone %>
</p>

<p>
  <strong>Group ID:</strong>
  <%= @person.group_id %>
</p> 

<p>
  <strong>Group name:</strong>
  <%= @person.group.groupname %>
</p> 
<%= link_to 'Back to List', people_path %>